#!/bin/bash

DIR="${BASH_SOURCE[0]}";
if ([ -h "${DIR}" ]) then
  while([ -h "${DIR}" ]) do cd `dirname "$DIR"`; DIR=`readlink "${DIR}"`; done
fi
cd `dirname ${DIR}` > /dev/null
DIR=`pwd`;

sudo $DIR/displaylink.sh